# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master
- develop

pool:
  vmImage: ubuntu-latest

container: ubuntu:18.04


steps:

- task: CmdLine@2
  inputs:
    script: |
      sudo apt-get update -y && sudo apt-get upgrade -y
      sudo apt install default-jdk -y
      sudo apt-get install wget -y 
      cd /tmp 
      wget https://apache.panu.it/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
      sudo tar -xvzf apache-maven-3.6.3-bin.tar.gz
      cp -r apache-maven-3.6.3 /opt/maven
      echo "export JAVA_HOME=/usr/lib/jvm/default-java
        export M2_HOME=/opt/maven
        export MAVEN_HOME=/opt/maven
        export PATH=${M2_HOME}/bin:${PATH}" >> /etc/profile.d/maven.sh
      chmod 755 /etc/profile.d/maven.sh
      source /etc/profile.d/maven.sh 
  displayName: ListingFileDir

#- task: Maven@3
#  inputs:
#    mavenPomFile: 'pom.xml'
#    mavenOptions: '-Xmx3072m'
#    javaHomeOption: 'JDKVersion'
#    jdkVersionOption: '1.8'
#    jdkArchitectureOption: 'x64'
#    publishJUnitResults: true
#    testResultsFiles: '**/surefire-reports/TEST-*.xml'
#    goals: 'package'

#- task: PublishCodeCoverageResults@1
#  inputs:
#    codeCoverageTool: "JaCoCo"
#    summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/site/jacoco/jacoco.xml"
#    reportDirectory: "$(System.DefaultWorkingDirectory)/**/site/jacoco"
#    failIfCoverageEmpty: true